server:
  port: 8080
  context-path=/LifeCust:

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3308/xiaolidatabases?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  http:
    encoding:
      charset=UTF-8:
  thymeleaf:
    suffix: .html
    servlet:
      content-type: text/html
    cache: false
    mode: LEGACYHTML5
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**



